# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Basic
name:               "adam barnhard"
description: >
  I'm Adam Barnhard. I'm a software developer building
  solutions with JavaScript, Ruby, & Python, and Java 8.
  This is my personal blog.

author:
  name:             Adam Barnhard
  twitter:          adambarnhard
  github:           abarnhard
  linkedin:         adambarnhard
  email:            admbarn@gmail.com

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "adambarnhard"

# URL
url:             "http://adambarnhard.com"
# url:               "localhost:4000"
baseurl:           ""

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/Chicago
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  # - name:           "Projects"
  #   url:            "/projects"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Build settings
# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

# Markdown
markdown: kramdown
kramdown:
  imput: GFM

exclude: [vendor]
